export const GRADES = [
  { id: 'k',  label: 'K',   name: 'Kindergarten', animal: 'Bear with Butterfly',
    image:   'https://cdn.prod.website-files.com/64aa957da446d8dc44869f81/6a1c3784d9dab01e907030e8_k_no_bg.webp',
    imageBg: 'https://cdn.prod.website-files.com/64aa957da446d8dc44869f81/6a1c37b8caa064ef33b07d9d_k.webp',
    pfp:     'https://cdn.prod.website-files.com/64aa957da446d8dc44869f81/6a1c37c265d062b2a6d5c01d_k_pfp.webp',
    bg: '#BD9CEF', textColor: 'text-purple-900' },
  { id: '1',  label: '1st', name: '1st Grade',     animal: 'Raccoon with Flower',
    image:   'https://cdn.prod.website-files.com/64aa957da446d8dc44869f81/6a1c3784dd92b1af68e91caf_first_no_bg.webp',
    imageBg: 'https://cdn.prod.website-files.com/64aa957da446d8dc44869f81/6a1c3801b5cdd3b7b53d4b23_1st.webp',
    pfp:     'https://cdn.prod.website-files.com/64aa957da446d8dc44869f81/6a1c37b8b5992c08654f20cf_1_pfp.webp',
    bg: '#F8E37D', textColor: 'text-yellow-900' },
  { id: '2',  label: '2nd', name: '2nd Grade',     animal: 'Beaver with Crown',
    image:   'https://cdn.prod.website-files.com/64aa957da446d8dc44869f81/6a1c3784e28d1a7b0e881c57_second_no_bg.webp',
    imageBg: 'https://cdn.prod.website-files.com/64aa957da446d8dc44869f81/6a1c3801b939ef8e36b3806f_2nd.webp',
    pfp:     'https://cdn.prod.website-files.com/64aa957da446d8dc44869f81/6a1c37b8850dcc5431ce1aec_2_pfp.webp',
    bg: '#F5D4AA', textColor: 'text-orange-900' },
  { id: '3',  label: '3rd', name: '3rd Grade',     animal: 'Bear with Flower',
    image:   'https://cdn.prod.website-files.com/64aa957da446d8dc44869f81/6a1c3784ba03ba59ac82b694_third_no_bg.webp',
    imageBg: 'https://cdn.prod.website-files.com/64aa957da446d8dc44869f81/6a1c3801e28d1a7b0e884d32_3rd.webp',
    pfp:     'https://cdn.prod.website-files.com/64aa957da446d8dc44869f81/6a1c37b8b5cdd3b7b53d4000_3_pfp.webp',
    bg: '#C0EDE3', textColor: 'text-teal-900'   },
  { id: '4',  label: '4th', name: '4th Grade',     animal: 'Little Penguin',
    image:   'https://cdn.prod.website-files.com/64aa957da446d8dc44869f81/6a1c4a6dc4c72358e5634d16_fourth_no_bg.webp',
    imageBg: 'https://cdn.prod.website-files.com/64aa957da446d8dc44869f81/6a1c38011f5da43c33a0bd35_4th.webp',
    pfp:     'https://cdn.prod.website-files.com/64aa957da446d8dc44869f81/6a1c37b8b939ef8e36b3738f_4_pfp.webp',
    bg: '#DDC1A5', textColor: 'text-amber-900'  },
  { id: '5',  label: '5th', name: '5th Grade',     animal: 'Frog',
    image:   'https://cdn.prod.website-files.com/64aa957da446d8dc44869f81/6a1c37843cdc8575d581302e_fifth_no_bg.webp',
    imageBg: 'https://cdn.prod.website-files.com/64aa957da446d8dc44869f81/6a1c3801b5992c08654f3919_5th.webp',
    pfp:     'https://cdn.prod.website-files.com/64aa957da446d8dc44869f81/6a1c37b8850dcc5431ce1b03_5_pfp.webp',
    bg: '#B3BDF5', textColor: 'text-indigo-900' },
]

export const ACTIVITIES = {
  k:  [
    { id: 'k1', title: 'Counting Fun',      description: 'Count objects up to 20 with colorful pictures!',    points: 10, icon: '🔢', pdfUrl: null },
    { id: 'k2', title: 'Shape Safari',      description: 'Find and name shapes in the wild!',                 points: 10, icon: '🔵', pdfUrl: null },
    { id: 'k3', title: 'Number Match',      description: 'Match numbers to groups of objects.',               points: 10, icon: '✏️', pdfUrl: null },
    { id: 'k4', title: 'Big & Small',       description: 'Compare sizes and learn bigger vs smaller.',        points: 10, icon: '📏', pdfUrl: null },
    { id: 'k5', title: 'Color & Count',     description: 'Color pictures and count what you colored!',        points: 10, icon: '🎨', pdfUrl: null },
    { id: 'k6', title: 'Pattern Play',      description: 'Spot and continue fun patterns.',                   points: 15, icon: '🌈', pdfUrl: null },
  ],
  '1': [
    { id: '1a', title: 'Add it Up!',        description: 'Practice addition facts up to 20.',                 points: 10, icon: '➕', pdfUrl: null },
    { id: '1b', title: 'Take Away',         description: 'Learn subtraction with fun stories.',               points: 10, icon: '➖', pdfUrl: null },
    { id: '1c', title: 'Tens & Ones',       description: 'Explore place value with tens and ones blocks.',    points: 15, icon: '🧱', pdfUrl: null },
    { id: '1d', title: 'Telling Time',      description: 'Read clocks to the hour and half hour.',            points: 15, icon: '🕐', pdfUrl: null },
    { id: '1e', title: 'Measure Up',        description: 'Measure objects using non-standard units.',         points: 10, icon: '📐', pdfUrl: null },
    { id: '1f', title: 'Graph It!',         description: 'Create and read simple bar graphs.',                points: 15, icon: '📊', pdfUrl: null },
  ],
  '2': [
    { id: '2a', title: 'Double Trouble',    description: 'Master doubles facts for fast addition!',           points: 10, icon: '✌️', pdfUrl: null },
    { id: '2b', title: 'Skip Counting',     description: 'Count by 2s, 5s, and 10s like a pro.',             points: 10, icon: '🦘', pdfUrl: null },
    { id: '2c', title: 'Place Value Park',  description: 'Hundreds, tens, and ones — oh my!',                points: 15, icon: '🏞️', pdfUrl: null },
    { id: '2d', title: 'Money Math',        description: 'Count coins and make change.',                      points: 15, icon: '🪙', pdfUrl: null },
    { id: '2e', title: 'Shape Detective',   description: 'Identify 2D and 3D shapes in the real world.',     points: 10, icon: '🔎', pdfUrl: null },
    { id: '2f', title: 'Word Problems',     description: 'Solve math stories with addition and subtraction.', points: 20, icon: '📖', pdfUrl: null },
  ],
  '3': [
    { id: '3a', title: 'Times Tables',      description: 'Master multiplication facts 0–10.',                 points: 15, icon: '✖️', pdfUrl: null },
    { id: '3b', title: 'Division Dojo',     description: 'Learn division as the opposite of multiplication.', points: 15, icon: '➗', pdfUrl: null },
    { id: '3c', title: 'Fraction Forest',   description: 'Explore halves, thirds, and fourths.',              points: 20, icon: '🍕', pdfUrl: null },
    { id: '3d', title: 'Area & Perimeter',  description: 'Measure the space around and inside shapes.',       points: 20, icon: '📦', pdfUrl: null },
    { id: '3e', title: 'Rounding Rocks',    description: 'Round numbers to the nearest 10 and 100.',          points: 15, icon: '🪨', pdfUrl: null },
    { id: '3f', title: 'Data Camp',         description: 'Read and create pictographs and bar graphs.',       points: 15, icon: '📈', pdfUrl: null },
  ],
  '4': [
    { id: '4a', title: 'Multi-Digit Math',  description: 'Multiply and divide bigger numbers.',               points: 20, icon: '💪', pdfUrl: null },
    { id: '4b', title: 'Fraction Fun',      description: 'Add and subtract fractions with like denominators.', points: 20, icon: '🍰', pdfUrl: null },
    { id: '4c', title: 'Decimal Point',     description: 'Understand decimals to tenths and hundredths.',     points: 20, icon: '🎯', pdfUrl: null },
    { id: '4d', title: 'Angle Adventure',   description: 'Measure and classify angles.',                      points: 20, icon: '📐', pdfUrl: null },
    { id: '4e', title: 'Factor Finder',     description: 'Find factors and multiples of whole numbers.',      points: 15, icon: '🔍', pdfUrl: null },
    { id: '4f', title: 'Convert It!',       description: 'Convert units of measurement.',                     points: 20, icon: '⚖️', pdfUrl: null },
  ],
  '5': [
    { id: '5a', title: 'Fraction Master',   description: 'Multiply and divide fractions — you got this!',    points: 25, icon: '🏆', pdfUrl: null },
    { id: '5b', title: 'Decimal Dash',      description: 'Operations with decimals at full speed.',           points: 25, icon: '⚡', pdfUrl: null },
    { id: '5c', title: 'Volume Quest',      description: 'Calculate volume of rectangular prisms.',           points: 25, icon: '📦', pdfUrl: null },
    { id: '5d', title: 'Coordinate Grid',   description: 'Plot and read points on a coordinate plane.',       points: 25, icon: '🗺️', pdfUrl: null },
    { id: '5e', title: 'Order of Ops',      description: 'Apply PEMDAS to solve complex expressions.',        points: 30, icon: '🧮', pdfUrl: null },
    { id: '5f', title: 'Data & Stats',      description: 'Analyze data sets, find mean and median.',          points: 25, icon: '📉', pdfUrl: null },
  ],
}

export const BADGES = [
  // Row 1
  { id: 'first_camper',    name: 'First Camper',     description: 'Complete your first login',            icon: '⛺', color: 'bg-forest-100 text-forest-800',     condition: s => true },
  { id: 'daily_explorer',  name: 'Daily Explorer',   description: 'Complete your first check-in',         icon: '🧭', color: 'bg-sky-100 text-sky-800',           condition: s => s.checkIns >= 1 },
  { id: 'early_bird',      name: 'Early Bird',       description: 'Check in 3 days in a row',             icon: '🐦', color: 'bg-sky-100 text-sky-700',           condition: s => s.streak >= 3 },
  { id: 'five_day_streak', name: 'Five Day Streak',  description: 'Check in five days in a row',          icon: '🔥', color: 'bg-campfire-100 text-campfire-800', condition: s => s.streak >= 5 },
  { id: 'ten_day_streak',  name: 'Ten Day Streak',   description: 'Check in ten days in a row',           icon: '💥', color: 'bg-campfire-100 text-campfire-700', condition: s => s.streak >= 10 },
  { id: 'number_ninja',    name: 'Number Ninja',     description: 'Complete five activities',              icon: '🥷', color: 'bg-sunshine-100 text-sunshine-600', condition: s => s.activitiesCompleted >= 5 },
  { id: 'super_star',      name: 'Super Star',       description: 'Complete ten activities',               icon: '🌠', color: 'bg-sunshine-100 text-sunshine-600', condition: s => s.activitiesCompleted >= 10 },
  { id: 'fraction_master', name: 'Fraction Master',  description: 'Complete a fraction activity',         icon: '🍕', color: 'bg-campfire-50 text-campfire-700',  condition: s => s.completedFraction },
  // Row 2
  { id: 'math_star',       name: 'Math Star',        description: 'Earn 100 points',                      icon: '⭐', color: 'bg-sunshine-100 text-sunshine-600', condition: s => s.points >= 100 },
  { id: 'point_collector', name: 'Point Collector',  description: 'Earn 250 points',                      icon: '💰', color: 'bg-sunshine-100 text-sunshine-500', condition: s => s.points >= 250 },
  { id: 'high_scorer',     name: 'High Scorer',      description: 'Earn 500 points',                      icon: '🏅', color: 'bg-sunshine-100 text-sunshine-500', condition: s => s.points >= 500 },
  { id: 'trail_blazer',    name: 'Trail Blazer',     description: 'Complete all activities in a grade',   icon: '🥾', color: 'bg-forest-100 text-forest-700',     condition: s => s.completedGrade },
  { id: 'comeback_kid',    name: 'Comeback Kid',     description: 'Complete the same activity twice',     icon: '🔁', color: 'bg-sky-100 text-sky-700',           condition: s => s.maxActivityRepeats >= 2 },
  { id: 'super_repeater',  name: 'Super Repeater',   description: 'Complete the same activity 5 times',   icon: '🌀', color: 'bg-campfire-50 text-campfire-700',  condition: s => s.maxActivityRepeats >= 5 },
  { id: 'legend',          name: 'Math Legend',      description: 'Complete the same activity 10 times',  icon: '🌟', color: 'bg-sunshine-100 text-sunshine-600', condition: s => s.maxActivityRepeats >= 10 },
  { id: 'camp_champion',   name: 'Camp Champion',    description: 'Earn ten badges',                      icon: '🏆', color: 'bg-sunshine-100 text-sunshine-600', condition: s => s.badges >= 10 },
]

export const MOCK_STUDENT = {
  student_id: '',
  display_name: 'Guest Camper',
  email: '',
  grade: null,
  points: 0,
  created_at: new Date().toISOString(),
  activitiesCompleted: 0,
  streak: 0,
  checkIns: 0,
  completedFraction: false,
  completedGrade: false,
  badges: 0,
  recentActivity: [],
}
